baseURL = "http://k-33.at/"
languageCode = "en-us"
title = "k-33 | IT services with a focus on graphs"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "de"

# Site Params
[params]
    logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
[Languages]
    ############# 1 - Site en ENGLISH
    [Languages.en]
    languageName = "English"
    weight = 1
    languageCode = "en-uk"
    title = "k-33 Experts"
    dateFormat = "January 1, 2018"

    home = "EN Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "As experts on graphs and technologies based on graphs k-33 offers knowledge and experience through various services."
    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerAboutTitle = "About"
    footerSubscribeTitle = "Newsletter"
    footerSubscribeBtnText = "Subscribe now"
    footerSubscribePlaceholderText = "Enter email"


    [Languages.en.cookies]
    dismiss = "I Agree."
    message = "We use cookies to offer you a better experience and to gain insight into site traffic. By continuing to use this website, you consent to the use of cookies as explained in our "
    href = "privacy"
    link = "privacy policy."

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "Your guide to graphs!"
        description = "Welcome to k-33"

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "ENGLISH Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "ENGLISH Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        firma = "k-33 e.U."
        name = "Michael Dirnberger"
        street = "Burgenlandstraße 9"
        town = "9800 Spittal an der Drau"
        country = "Austria"
        address = "Burgenlandstraße 9, 9800 Spittal an der Drau, Austria"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        mail = "office@k-33.at"
        purpose = "Services in automatic data processing and information technology"
        uid = "VAT"
        companynumber = "Firmenbuchnummer"
        companycourt = "Firmenbuchgericht"
        memberships = "WKÖ"
        regulation = "Gewerbeordnung"
        regulator = "Magistrat Graz"
        content = "Information on modern technologies centering around the topic of graphs."
        facebook= ""
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= ""
        instagram= ""
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Your Guide To Graphs"
        subtitle= "Get to know us and find out what we can do for you in a free strategy session. We are looking forward to hear from you."
        btnText = "Contact Us"

    ############ 3 - Site in German
    [Languages.de]
    languageName = "Deutsch"
    weight = 2
    languageCode = "de-at"
    title = "GERMAN Example site multi-language"
    dateFormat = "2 January 2006"

    home = "DE Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "Als Experte im Bereich Graphen und darauf basierenden Technologien bietet k-33 Wissen und Erfahrung in Form von Dienstleistungen an."
    footerServiceTitle = "Leistungen"
    footerQuicklinkTitle = "Quick links"
    footerAboutTitle = "Über uns"
    footerSubscribeTitle = "Newsletter"
    footerSubscribeBtnText = "Jetzt anmelden"
    footerSubscribePlaceholderText = "Email"

    [Languages.de.cookies]
    dismiss = "Ich stimme zu."
    message = "Wir verwenden Cookies um die Bereitstellung unsere Seite zu verbessern und um die Reichweite zu messen. Durch die Verwendung dieser Website stimmen Sie der Verwendung von Cookies zu, siehe "
    href = "privacy"
    link = "Datenschutzerklärung."

    # Hero Area Section
    [Languages.de.params.hero]
        enable  = true
        heading = "Your guide to graphs!"
        description = "Willkommen bei k-33"

    # Blog Section On Homepage
    [Languages.de.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "GERMAN Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.de.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "GERMAN Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        firma = "k-33 e.U."
        name = "Michael Dirnberger"
        street = "Burgenlandstraße 9"
        town = "9800 Spittal an der Drau"
        country = "Austria"
        address = "Burgenlandstraße 9, 9800 Spittal an der Drau, Austria"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        mail = "office@k-33.at"
        purpose = "Dienstleistungen in der automatischen Datenverarbeitung und Informationstechnik"
        uid = "UID"
        companynumber = "Firmenbuchnummer"
        companycourt = "Firmenbuchgericht"
        memberships = "WKÖ"
        regulation = "Gewerbeordnung"
        regulator = "Magistrat Graz"
        content = "Information zu modernen Technologien rund um das Thema Graphen."
        facebook= ""
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= ""
        instagram= ""
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.de.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Your Guide To Graphs"
        subtitle= "Lernen Sie uns kennen und erfahren Sie was wir für Sie tun können im kostenlosen Erstgespräch. Wir freuen uns auf Sie."
        btnText = "Kontakt"


# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "home"
        url     = ""
        weight  = 1
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "applications"
        url     = "applications"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "academy"
        url     = "https://k-33-academy.thinkific.com/collections"
        weight  = 6
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 7

    # Footer Service Menu
    [[menu.service]]
        name    = "checkup"
        url     = "service/#checkup"
        weight  = 1
    [[menu.service]]
        name    = "keynote"
        url     = "service/#keynote"
        weight  = 2
    [[menu.service]]
        name    = "consultation"
        url     = "service/#consultation"
        weight  = 3
    [[menu.service]]
        name    = "workshop"
        url     = "service/#workshop"
        weight  = 4


    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "contact2"
        url     = "contact"
        weight  = 1
    [[menu.quicklink]]
        name    = "faqs"
        url     = "faqs"
        weight  = 2
    [[menu.quicklink]]
        name    = "privacy"
        url     = "privacy"
        weight  = 3
    [[menu.quicklink]]
        name    = "legal"
        url     = "legal"
        weight  = 4
