baseURL = "http://k-33.at/"
languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "de"

# Site Params
[params]
    logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
[Languages]
    ############# 1 - Site en ENGLISH
    [Languages.en]
    languageName = "English"
    weight = 1
    languageCode = "en-uk"
    title = "ENGLISH Example site multi-language"
    dateFormat = "January 2, 2006"

    home = "EN Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "ENGLISH Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
    footerServiceTitle = "ENGLISH Service"
    footerQuicklinkTitle = "ENGLISH Quicklinks"
    footerAboutTitle = "ENGLISH About"
    footerSubscribeTitle = "ENGLISH Subscribe"

    [Languages.en.cookies]
    dismiss = "I Agree."
    message = "We use cookies to offer you a better experience and to gain insight into site traffic. By continuing to use this website, you consent to the use of cookies as explained in our "
    href = "privacy"
    link = "privacy policy."

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "ENGLISH We love to make brands grow"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
        button  = false
        btnText = "Know More"
        btnURL  = "https://themefisher.com/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "ENGLISH Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "ENGLISH Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        firma = "k-33 e.U."
        name = "Michael Dirnberger"
        street = "Burgenlandstraße 9"
        town = "9800 Spittal an der Drau"
        country = "Austria"
        address = "Burgenlandstraße 9, 9800 Spittal an der Drau, Austria"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        mail = "office@k-33.at"
        purpose = "Services in automatic data processing and information technology"
        uid = "VAT"
        companynumber = "Firmenbuchnummer"
        companycourt = "Firmenbuchgericht"
        memberships = "WKÖ"
        regulation = "Gewerbeordnung"
        regulator = "Magistrat Graz"
        content = "Information on modern technologies centering around the topic of graphs."
        facebook= ""
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= ""
        instagram= ""
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "ENGLISH Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

    ############ 3 - Site in German
    [Languages.de]
    languageName = "Deutsch"
    weight = 2
    languageCode = "de-at"
    title = "GERMAN Example site multi-language"
    dateFormat = "2 January 2006"

    home = "DE Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "GERMAN Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
    footerServiceTitle = "GERMAN Services"
    footerQuicklinkTitle = "GERMAN Quick links"
    footerAboutTitle = "GERMAN About"
    footerSubscribeTitle = "GERMAN Subscribe"

    [Languages.de.cookies]
    dismiss = "Ich stimme zu."
    message = "Wir verwenden Cookies um die Bereitstellung unsere Seite zu verbessern und um den Nutzerstrom zu beobachten. Durch die Verwendung dieser Website stimmen Sie der Verwendung von Cookies zu, siehe "
    href = "privacy"
    link = "Datenschutzerklärung."

    # Hero Area Section
    [Languages.de.params.hero]
        enable  = true
        heading = "GERMAN We love to make brands grow"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
        button  = false
        btnText = "Know More"
        btnURL  = "https://themefisher.com/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # Blog Section On Homepage
    [Languages.de.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "GERMAN Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.de.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "GERMAN Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        firma = "k-33 e.U."
        name = "Michael Dirnberger"
        street = "Burgenlandstraße 9"
        town = "9800 Spittal an der Drau"
        country = "Austria"
        address = "Burgenlandstraße 9, 9800 Spittal an der Drau, Austria"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        mail = "office@k-33.at"
        purpose = "Dienstleistungen in der automatischen Datenverarbeitung und Informationstechnik"
        uid = "UID"
        companynumber = "Firmenbuchnummer"
        companycourt = "Firmenbuchgericht"
        memberships = "WKÖ"
        regulation = "Gewerbeordnung"
        regulator = "Magistrat Graz"
        content = "Information zu modernen Technologien rund um das Thema Graphen."
        facebook= ""
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= ""
        instagram= ""
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.de.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "GERMAN Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Let's talk"


# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "home"
        url     = ""
        weight  = 1
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "applications"
        url     = "applications"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "academy"
        url     = "https://k-33-academy.thinkific.com/collections"
        weight  = 6
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 7

    # Footer Service Menu
    [[menu.service]]
        name    = "checkup"
        url     = "service/#checkup"
        weight  = 1
    [[menu.service]]
        name    = "keynote"
        url     = "service/#keynote"
        weight  = 2
    [[menu.service]]
        name    = "consultation"
        url     = "service/#consultation"
        weight  = 3
    [[menu.service]]
        name    = "workshop"
        url     = "service/#workshop"
        weight  = 4


    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "contact2"
        url     = "contact"
        weight  = 1
    [[menu.quicklink]]
        name    = "faqs"
        url     = "faqs"
        weight  = 2
    [[menu.quicklink]]
        name    = "privacy"
        url     = "privacy"
        weight  = 3
    [[menu.quicklink]]
        name    = "legal"
        url     = "legal"
        weight  = 4
