baseURL = "https://k33experts.com/"
languageCode = "en-us"
title = "k33 Experts | IT services with a focus on graphs"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "de"

# Site Params
[params]
    logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
[Languages]
    ############# 1 - Site en ENGLISH
    [Languages.en]
    languageName = "English"
    weight = 1
    languageCode = "en-uk"
    title = "k33 Experts - Your Guide To Graphs"
    dateFormat = "January 1, 2018"

    home = "EN Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "k33 Experts provides knowledge services regarding data analytics and software engineering based on graphs."
    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerAboutTitle = "About"
    footerSubscribeTitle = "Keep in touch"
    footerSubscribeBtnText = "Subscribe now"
    footerSubscribePlaceholderText = "Enter email"
    footerSubscribeMailchimp = "https://eepurl.com/goqHb5"


    [Languages.en.cookies]
    dismiss = "I Agree."
    message = "We use cookies to offer you a better experience and to gain insight into site traffic. By continuing to use this website, you consent to the use of cookies as explained in our "
    href = "privacy"
    link = "privacy policy."

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "Your guide to graphs!"
        description = "Welcome to k33 Experts in Graz"

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "ENGLISH Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "Interested?"
        title   = "Drop us a note!"
        subtitle= ""
        firma = "k33 Experts e.U."
        name = "Michael Dirnberger"
        street = "Mühlgasse 30"
        town = "8020 Graz"
        country = "Austria"
        address = "Mühlgasse 30, 8020 Graz, Austria"
        phone   = "0043 670 408 15 60"
        fax     = ""
        mail = "contact@k33experts.com"
        purpose = "Services in automatic data processing and information technology"
        uid = "ATU74352201"
        companynumber = "FN 512847 m"
        companycourt = "Landesgericht f. ZRS Graz, Marburgerkai 49, 8010 Graz"
        memberships = "WKÖ"
        regulation = "Gewerbeordnung"
        regulator = "Magistrat Graz"
        content = "Information on modern technologies centering around the topic of graphs."
        facebook= ""
        twitter = "https://twitter.com/k33experts"
        linkedin= "https://www.linkedin.com/in/michael-dirnberger-0ba1b0171/"
        dribbble= ""
        instagram= ""
        mapLatitude = "47.074281"
        mapLongitude= "15.427680"
        mapMarker   = "images/marker.png"
        mapImage  = "images/map.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "k33 Experts - Your Guide To Graphs"
        subtitle= "Get to know us and find out what we can do for you in a free strategy session. We are looking forward to hearing from you."
        btnText = "Contact Us"

    ############ 3 - Site in German
    [Languages.de]
    languageName = "Deutsch"
    weight = 2
    languageCode = "de-at"
    title = "k33 Experts - Your Guide To Graphs"
    dateFormat = "2 January 2006"

    home = "DE Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "k33 Experts liefert Wissensdienstleistungen im Bereich Data Science und Software Engineering mit Fokus auf Graphen."
    footerServiceTitle = "Leistungen"
    footerQuicklinkTitle = "Quick links"
    footerAboutTitle = "Über uns"
    footerSubscribeTitle = "Mailingliste"
    footerSubscribeBtnText = "Jetzt anmelden"
    footerSubscribePlaceholderText = "Email"
    footerSubscribeMailchimp = "https://eepurl.com/goqHb5"

    [Languages.de.cookies]
    dismiss = "Ich stimme zu."
    message = "Wir verwenden Cookies um die Bereitstellung unsere Seite zu verbessern und um die Reichweite zu messen. Durch die Verwendung dieser Website stimmen Sie der Verwendung von Cookies zu, siehe "
    href = "privacy"
    link = "Datenschutzerklärung."

    # Hero Area Section
    [Languages.de.params.hero]
        enable  = true
        heading = "Your guide to graphs!"
        description = "Willkommen bei k33 Experts in Graz"

    # Blog Section On Homepage
    [Languages.de.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "GERMAN Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.de.params.contact]
        enable  = true
        topTitle= "Interesse?"
        title   = "Schreiben Sie uns doch!"
        subtitle= ""
        firma = "k33 Experts e.U."
        name = "Michael Dirnberger"
        street = "Mühlgasse 30"
        town = "8020 Graz"
        country = "Austria"
        address = "Mühlgasse 30, 8020 Graz, Austria"
        phone   = "0043 670 408 15 60"
        fax     = ""
        mail = "contact@k33experts.com"
        purpose = "Dienstleistungen in der automatischen Datenverarbeitung und Informationstechnik"
        uid = "ATU74352201"
        companynumber = "FN 512847 m"
        companycourt = "Landesgericht f. ZRS Graz, Marburgerkai 49, 8010 Graz"
        memberships = "WKÖ"
        regulation = "Gewerbeordnung"
        regulator = "Magistrat Graz"
        content = "Information zu modernen Technologien rund um das Thema Graphen."
        facebook= ""
        twitter = "https://twitter.com/k33experts"
        linkedin= "https://www.linkedin.com/in/michael-dirnberger-0ba1b0171/"
        dribbble= ""
        instagram= ""
        mapLatitude = "47.074281"
        mapLongitude= "15.427680"
        mapMarker   = "images/marker.png"
        mapImage  = "images/map.png"

    # Call to Action Section on About Page
    [Languages.de.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "k33 Experts - Your Guide To Graphs"
        subtitle= "Lernen Sie uns kennen und erfahren Sie im kostenlosen Erstgespräch was wir für Sie tun können. Wir freuen uns auf Sie."
        btnText = "Kontakt"


# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "home"
        url     = ""
        weight  = 1
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    # [[menu.nav]]
    #     name    = "applications"
    #     url     = "applications"
    #     weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "https://blog.k33experts.com"
        weight  = 6
    [[menu.nav]]
        name    = "academy"
        url     = "https://k33-academy.thinkific.com/courses"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 7

    # Footer Service Menu
    [[menu.service]]
        name    = "checkup"
        url     = "service/#checkup"
        weight  = 1
    [[menu.service]]
        name    = "keynote"
        url     = "service/#keynote"
        weight  = 2
    [[menu.service]]
        name    = "consultation"
        url     = "service/#consultation"
        weight  = 3
    [[menu.service]]
        name    = "workshop"
        url     = "service/#workshop"
        weight  = 4


    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "contact2"
        url     = "contact"
        weight  = 1
    [[menu.quicklink]]
        name    = "faqs"
        url     = "faqs"
        weight  = 2
    [[menu.quicklink]]
        name    = "privacy"
        url     = "privacy"
        weight  = 3
    [[menu.quicklink]]
        name    = "legal"
        url     = "legal"
        weight  = 4
    [[menu.quicklink]]
        name    = "terms"
        url = "terms"
        weight  = 5
